// <auto-generated />
using EmployeeDepartmentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeDepartmentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeDepartmentAPI.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("EmployeeDepartmentAPI.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "Alice Johnson",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FullName = "Bob Smith",
                            Position = "HR Manager"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            FullName = "Charlie Brown",
                            Position = "Sales Associate"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            FullName = "David Lee",
                            Position = "Backend Developer"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            FullName = "Emma Davis",
                            Position = "Frontend Developer"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            FullName = "Fiona Clark",
                            Position = "QA Engineer"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            FullName = "George Hall",
                            Position = "DevOps Engineer"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            FullName = "Hannah White",
                            Position = "Recruiter"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 2,
                            FullName = "Ian Martinez",
                            Position = "HR Assistant"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 2,
                            FullName = "Jane Foster",
                            Position = "HR Generalist"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 3,
                            FullName = "Kevin King",
                            Position = "Sales Executive"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 3,
                            FullName = "Lily Green",
                            Position = "Account Manager"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            FullName = "Mark Turner",
                            Position = "Sales Representative"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 1,
                            FullName = "Nina Adams",
                            Position = "Business Analyst"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 1,
                            FullName = "Oliver Scott",
                            Position = "UI/UX Designer"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 2,
                            FullName = "Paula Baker",
                            Position = "HR Coordinator"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            FullName = "Quentin Ross",
                            Position = "Software Architect"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            FullName = "Rachel Evans",
                            Position = "Technical Writer"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 3,
                            FullName = "Steve Young",
                            Position = "Sales Consultant"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 3,
                            FullName = "Tina Allen",
                            Position = "Customer Success"
                        });
                });

            modelBuilder.Entity("EmployeeDepartmentAPI.Data.Models.Employee", b =>
                {
                    b.HasOne("EmployeeDepartmentAPI.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EmployeeDepartmentAPI.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
